### ISSUE TITLE
MIND_NEWS_PATH problems

### ISSUE THREAD

**Issue by baebae-dev** [msnews/MIND#7]
hi, thanks to your crawler script.
I did run your code.

but, i having some problem with code 
"with open(os.environ["MIND_NEWS_PATH"], 'r') as f:" 

error message was this
"raise KeyError(key) from None
KeyError: 'MIND_NEWS_PATH'"

is it caused by path?
then i need your computer "MIND_NEWS_PATH" path?

**Comment by itszyin** [comment]
I also met this problem. In my opinion, this environment variable should direct to the download news.tsv file such as `{YOUR_DATA_PATH}/MIND/small_data/train_data/news.tsv`.

So I tried following commands
```
> export MIND_NEWS_PATH={YOUR_DATA_PATH}/MIND/small_data/train_data/news.tsv
# then
> scrapy crawl msn -o msn.json
```

P.S. After doing this , the script may also not be running. You can read my PR: [fix tsv parsing](https://github.com/msnews/MIND/pull/6/commits/2023c8a77879d35635f6e7ce8b0102c7df4fd8bc) and change some codes.

**Comment by baeyuna97** [comment]
oh! thank you for your reply.

but as i saw,
data 6th column mean urls. right?
then,  this column data can't parse the web

but is it possible if i use this git crawler script???

**Comment by baebae-dev** [comment]
thanks u for your reply!

thans to u,
i can run this code

but it have a parsing problem yet......

it's origin data 6th columns mean url
but its raw column data can't parse cause of license....

so as i know cause of that organizer give this script

but when i run this code 
`scrapy crawl msn -o msn.json`
also have a error 
"<GET https://assets.msn.com/labs/mind/AADlomf.html> (failed 2 times): 503 Service Unavailable"

Am I doing something wrong?

**Comment by itszyin** [comment]
> thanks u for your reply!
> 
> thans to u,
> i can run this code
> 
> but it have a parsing problem yet......
> 
> it's origin data 6th columns mean url
> but its raw column data can't parse cause of license....
> 
> so as i know cause of that organizer give this script
> 
> but when i run this code
> `scrapy crawl msn -o msn.json`
> also have a error
> "<GET [https://assets.msn.com/labs/mind/AADlomf.html>](https://assets.msn.com/labs/mind/AADlomf.html%3E) (failed 2 times): 503 Service Unavailable"
> 
> Am I doing something wrong?

No, for the large dataset I also met this problem. But small dataset can run successful.
